"""correction

Revision ID: f143904d978a
Revises: bf9218f3f206
Create Date: 2026-04-03 09:38:53.617445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f143904d978a'
down_revision: Union[str, None] = 'bf9218f3f206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default='draft', nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('spend', sa.NUMERIC(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('impressions', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('clicks', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('conversions', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('key_competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objective', sa.VARCHAR(length=50), nullable=True),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('avg_conversion_value', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('creative_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_deleted_at'), 'campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaigns_user_uid'), 'campaigns', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_user_uid'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_deleted_at'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
