import jsPDF from 'jspdf';

export const generateBriefPdf = (aiBrief, campaignDetails) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  let y = 20;
  
  // Helper to check for page breaks
  const checkPageBreak = (requiredSpace) => {
    if (y + requiredSpace > doc.internal.pageSize.height - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // --- DOCUMENT HEADER ---
  doc.setFillColor(79, 70, 229); // Purple
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("AI Creative Brief", margin, 18, { align: 'left' });
  doc.setFontSize(12);
  doc.text("Generated by AdDash", pageWidth - margin, 18, { align: 'right' });
  
  y = 55;
  doc.setTextColor(0, 0, 0);

  // --- CAMPAIGN CONTEXT ---
  if (campaignDetails) {
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text(campaignDetails.name || "Campaign Name", margin, y);
    y += 8;
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text(`Client: ${campaignDetails.client || 'N/A'} | Objective: ${campaignDetails.objective || 'N/A'}`, margin, y);
    y += 6;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;
  }

  // --- SECTION HELPER ---
  const addSectionTitle = (title) => {
    checkPageBreak(15);
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text(title, margin, y);
    y += 8;
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(11);
  };

  // --- 1. TITLE SUGGESTION ---
  addSectionTitle("1. Campaign Title Suggestion");
  doc.text(aiBrief.campaign_title_suggestion, margin + 5, y, { maxWidth: pageWidth - (margin * 2) });
  y += 10;

  // --- 2. HEADLINE OPTIONS ---
  addSectionTitle("2. Headline Options");
  aiBrief.headline_options.forEach((h, i) => {
    checkPageBreak(8);
    doc.text(`${i + 1}. ${h}`, margin + 5, y, { maxWidth: pageWidth - (margin * 2) });
    y += 7;
  });
  y += 5;

  // --- 3. TONE OF VOICE ---
  addSectionTitle("3. Tone of Voice Guide");
  const toneLines = doc.splitTextToSize(aiBrief.tone_of_voice_guide, pageWidth - (margin * 2));
  toneLines.forEach(line => {
    checkPageBreak(6);
    doc.text(line, margin + 5, y);
    y += 6;
  });
  y += 5;

  // --- 4. RECOMMENDED CHANNELS ---
  addSectionTitle("4. Recommended Channels");
  aiBrief.recommended_channels.forEach(ch => {
    checkPageBreak(8);
    doc.text(`• ${ch}`, margin + 5, y);
    y += 7;
  });
  y += 5;

  // --- 5. BUDGET ALLOCATION ---
  addSectionTitle("5. Budget Allocation");
  if (aiBrief.budget_allocation_percentages) {
    const entries = Object.entries(aiBrief.budget_allocation_percentages);
    entries.forEach(([channel, percent], i) => {
      checkPageBreak(12);
      
      // Draw a mini progress bar
      const barY = y + 2;
      const barWidth = pageWidth - (margin * 2) - 60;
      doc.setFillColor(240, 240, 240);
      doc.roundedRect(margin + 60, barY, barWidth, 5, 2, 2, 'F');
      
      doc.setFillColor(79, 70, 229);
      doc.roundedRect(margin + 60, barY, barWidth * (percent / 100), 5, 2, 2, 'F');

      // Text
      doc.setFont(undefined, 'bold');
      const channelName = channel.replace(/_/g, ' ').charAt(0).toUpperCase() + channel.replace(/_/g, ' ').slice(1);
      doc.text(channelName, margin + 5, y + 3);
      
      doc.setFont(undefined, 'normal');
      doc.text(`${percent}%`, pageWidth - margin - 5, y + 3, { align: 'right' });
      
      y += 15;
    });
  }
  y += 5;

  // --- 6. KEY VISUAL DIRECTION ---
  addSectionTitle("6. Key Visual Direction (Hero Concept)");
  const visualLines = doc.splitTextToSize(aiBrief.key_visual_direction, pageWidth - (margin * 2));
  visualLines.forEach(line => {
    checkPageBreak(6);
    doc.text(line, margin + 5, y);
    y += 6;
  });

  // --- SAVE ---
  const fileName = `${(campaignDetails?.name || 'Campaign').replace(/\s+/g, '_')}_Brief.pdf`;
  doc.save(fileName);
};